// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PlaywrightTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class НастройкиАккаунтаFeature : object, Xunit.IClassFixture<НастройкиАккаунтаFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "AccountSettings.feature"
#line hidden
        
        public НастройкиАккаунтаFeature(НастройкиАккаунтаFeature.FixtureData fixtureData, PlaywrightTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Настройки аккаунта", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Запрет на просмотр фильмов для гостя (ТС-Г01)")]
        [Xunit.TraitAttribute("FeatureTitle", "Настройки аккаунта")]
        [Xunit.TraitAttribute("Description", "Запрет на просмотр фильмов для гостя (ТС-Г01)")]
        [Xunit.TraitAttribute("Category", "account")]
        public void ЗапретНаПросмотрФильмовДляГостяТС_Г01()
        {
            string[] tagsOfScenario = new string[] {
                    "account"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Запрет на просмотр фильмов для гостя (ТС-Г01)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 4
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
 testRunner.Given("пользователь не авторизован", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 6
 testRunner.When("открывает страницу фильма", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 7
 testRunner.And("нажимает кнопку \"Смотреть\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 8
 testRunner.Then("пользователь перенаправляется на страницу авторизации", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Запрет на просмотр фильмов для пользователя без подписки (ТС-АП01)")]
        [Xunit.TraitAttribute("FeatureTitle", "Настройки аккаунта")]
        [Xunit.TraitAttribute("Description", "Запрет на просмотр фильмов для пользователя без подписки (ТС-АП01)")]
        [Xunit.TraitAttribute("Category", "account")]
        public void ЗапретНаПросмотрФильмовДляПользователяБезПодпискиТС_АП01()
        {
            string[] tagsOfScenario = new string[] {
                    "account"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Запрет на просмотр фильмов для пользователя без подписки (ТС-АП01)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 11
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 12
 testRunner.Given("пользователь авторизован без подписки", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 13
 testRunner.When("открывает страницу фильма", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 14
 testRunner.And("нажимает кнопку \"Смотреть\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 15
 testRunner.Then("появляется сообщение о неудаче: \"Для просмотра фильма требуется активная подписка" +
                        ".\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 16
 testRunner.And("пользователь перенаправляется на страницу подписки", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Смена электронной почты на содержащую запрещенные символы (ТС-АП03)")]
        [Xunit.TraitAttribute("FeatureTitle", "Настройки аккаунта")]
        [Xunit.TraitAttribute("Description", "Смена электронной почты на содержащую запрещенные символы (ТС-АП03)")]
        [Xunit.TraitAttribute("Category", "account")]
        public void СменаЭлектроннойПочтыНаСодержащуюЗапрещенныеСимволыТС_АП03()
        {
            string[] tagsOfScenario = new string[] {
                    "account"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Смена электронной почты на содержащую запрещенные символы (ТС-АП03)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 19
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 20
 testRunner.Given("пользователь авторизован и находится в личном кабинете", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 21
 testRunner.When("вводит электронную почту \"alisa/@test.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 22
 testRunner.And("нажимает кнопку \"Сохранить изменения\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 23
 testRunner.Then("появляется сообщение о неудаче: \"Username \'alisa/@test.com\' is invalid, can only " +
                        "contain letters or digits.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 24
 testRunner.And("изменение не происходит", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Смена электронной почты на некорректную (ТС-АП04)")]
        [Xunit.TraitAttribute("FeatureTitle", "Настройки аккаунта")]
        [Xunit.TraitAttribute("Description", "Смена электронной почты на некорректную (ТС-АП04)")]
        [Xunit.TraitAttribute("Category", "account")]
        public void СменаЭлектроннойПочтыНаНекорректнуюТС_АП04()
        {
            string[] tagsOfScenario = new string[] {
                    "account"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Смена электронной почты на некорректную (ТС-АП04)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 27
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 28
 testRunner.Given("пользователь авторизован и находится в личном кабинете", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 29
 testRunner.When("вводит строку \"тест\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 30
 testRunner.And("нажимает кнопку \"Сохранить изменения\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 31
 testRunner.Then("появляется сообщение о неудаче: \"Username \'тест\' is invalid, can only contain let" +
                        "ters or digits.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 32
 testRunner.And("изменение не происходит", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Смена электронной почты на пустую строку (ТС-АП05)")]
        [Xunit.TraitAttribute("FeatureTitle", "Настройки аккаунта")]
        [Xunit.TraitAttribute("Description", "Смена электронной почты на пустую строку (ТС-АП05)")]
        [Xunit.TraitAttribute("Category", "account")]
        public void СменаЭлектроннойПочтыНаПустуюСтрокуТС_АП05()
        {
            string[] tagsOfScenario = new string[] {
                    "account"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Смена электронной почты на пустую строку (ТС-АП05)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 35
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 36
 testRunner.Given("пользователь авторизован и находится в личном кабинете", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 37
 testRunner.When("делает поле \"Электронная почта\" пустым", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 38
 testRunner.And("нажимает кнопку \"Сохранить изменения\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 39
 testRunner.Then("появляется сообщение о неудаче: \"Укажите электронную почту.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 40
 testRunner.And("изменение не происходит второе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Смена пароля с неверным текущим паролем (ТС-АП07)")]
        [Xunit.TraitAttribute("FeatureTitle", "Настройки аккаунта")]
        [Xunit.TraitAttribute("Description", "Смена пароля с неверным текущим паролем (ТС-АП07)")]
        [Xunit.TraitAttribute("Category", "account")]
        public void СменаПароляСНевернымТекущимПаролемТС_АП07()
        {
            string[] tagsOfScenario = new string[] {
                    "account"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Смена пароля с неверным текущим паролем (ТС-АП07)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 43
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 44
 testRunner.Given("пользователь авторизован и находится в личном кабинете", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 45
 testRunner.When("вводит некорректный текущий пароль \"wrongpassword\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 46
 testRunner.And("вводит новый пароль \"newpassword456\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 47
 testRunner.And("нажимает кнопку \"Сохранить изменения\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 48
 testRunner.Then("появляется сообщение о неудаче: \"Incorrect password.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 49
 testRunner.And("изменение не происходит", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Смена пароля на новый пароль менее 6 символов (ТС-АП08)")]
        [Xunit.TraitAttribute("FeatureTitle", "Настройки аккаунта")]
        [Xunit.TraitAttribute("Description", "Смена пароля на новый пароль менее 6 символов (ТС-АП08)")]
        [Xunit.TraitAttribute("Category", "account")]
        public void СменаПароляНаНовыйПарольМенее6СимволовТС_АП08()
        {
            string[] tagsOfScenario = new string[] {
                    "account"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Смена пароля на новый пароль менее 6 символов (ТС-АП08)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 52
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 53
 testRunner.Given("пользователь авторизован и находится в личном кабинете", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 54
 testRunner.When("вводит текущий пароль \"qwerty123!@#\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 55
 testRunner.And("вводит новый пароль \"12345\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 56
 testRunner.And("нажимает кнопку \"Сохранить изменения\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 57
 testRunner.Then("появляется сообщение о неудаче: \"The field NewPassword must be a string or array " +
                        "type with a minimum length of \'6\'.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 58
 testRunner.And("изменение не происходит второе", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Успешная смена электронной почты (ТС-АП02)")]
        [Xunit.TraitAttribute("FeatureTitle", "Настройки аккаунта")]
        [Xunit.TraitAttribute("Description", "Успешная смена электронной почты (ТС-АП02)")]
        [Xunit.TraitAttribute("Category", "account")]
        [Xunit.TraitAttribute("Category", "change-email")]
        public void УспешнаяСменаЭлектроннойПочтыТС_АП02()
        {
            string[] tagsOfScenario = new string[] {
                    "account",
                    "change-email"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Успешная смена электронной почты (ТС-АП02)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 61
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 62
 testRunner.Given("пользователь авторизован и находится в личном кабинете", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 63
 testRunner.When("вводит новую электронную почту \"alisa@gmail.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 64
 testRunner.And("нажимает кнопку \"Сохранить изменения\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 65
 testRunner.Then("появляется сообщение об успехе: \"Данные обновлены.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 66
 testRunner.And("пользователь не может совершить вход по старым данным", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 67
 testRunner.And("пользователь успешно выполняет вход по новым данным", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Успешная смена пароля (ТС-АП06)")]
        [Xunit.TraitAttribute("FeatureTitle", "Настройки аккаунта")]
        [Xunit.TraitAttribute("Description", "Успешная смена пароля (ТС-АП06)")]
        [Xunit.TraitAttribute("Category", "account")]
        [Xunit.TraitAttribute("Category", "change-password")]
        public void УспешнаяСменаПароляТС_АП06()
        {
            string[] tagsOfScenario = new string[] {
                    "account",
                    "change-password"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Успешная смена пароля (ТС-АП06)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 70
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 71
 testRunner.Given("пользователь авторизован и находится в личном кабинете", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 72
 testRunner.When("вводит текущий пароль \"qwerty123!@#\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 73
 testRunner.And("вводит новый пароль \"newpassword456\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 74
 testRunner.And("нажимает кнопку \"Сохранить изменения\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 75
 testRunner.Then("появляется сообщение об успехе: \"Данные обновлены.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 76
 testRunner.And("пользователь может произвести вход по новым данным", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Удаление аккаунта (ТС-АП09)")]
        [Xunit.TraitAttribute("FeatureTitle", "Настройки аккаунта")]
        [Xunit.TraitAttribute("Description", "Удаление аккаунта (ТС-АП09)")]
        [Xunit.TraitAttribute("Category", "account")]
        [Xunit.TraitAttribute("Category", "delete-account")]
        public void УдалениеАккаунтаТС_АП09()
        {
            string[] tagsOfScenario = new string[] {
                    "account",
                    "delete-account"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Удаление аккаунта (ТС-АП09)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 79
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 80
 testRunner.Given("пользователь авторизован и находится в личном кабинете", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 81
 testRunner.When("нажимает кнопку \"Удалить аккаунт\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 82
 testRunner.Then("появляется сообщение об успехе: \"Аккаунт удалён.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 83
 testRunner.And("пользователь выходит из аккаунта", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 84
 testRunner.And("пользователь больше не может зайти в свой аккаунт", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                НастройкиАккаунтаFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                НастройкиАккаунтаFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
